sudo: required
services:
  - docker
before_install:
  - docker build -t rinturi/docker-react -f Dockerfile.dev .
script:
  - docker run rinturi/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-south-1-810703848675"
  bucket_path: "frontend"
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"